// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Domain;

namespace Shop.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop.Domain.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "لوازم تحریر "
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "لوازم برقی خانگی"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "خواروبار"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "موادپروتیینی"
                        });
                });

            modelBuilder.Entity("Shop.Domain.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BrandName = "یونیبال",
                            CategoryId = 1L,
                            Description = "---------",
                            Price = 50000m,
                            ProductName = "روان نویس"
                        },
                        new
                        {
                            Id = 2L,
                            BrandName = "پنتر",
                            CategoryId = 1L,
                            Description = "-----",
                            Price = 10000m,
                            ProductName = "خودکار"
                        },
                        new
                        {
                            Id = 3L,
                            BrandName = "زبرا",
                            CategoryId = 1L,
                            Description = "-----",
                            Price = 20000m,
                            ProductName = "خودکار"
                        },
                        new
                        {
                            Id = 4L,
                            BrandName = "سامسونگ",
                            CategoryId = 2L,
                            Description = "-----",
                            Price = 3000000m,
                            ProductName = "جاروبرقی"
                        },
                        new
                        {
                            Id = 5L,
                            BrandName = "ال جی",
                            CategoryId = 2L,
                            Description = "-----",
                            Price = 9000000m,
                            ProductName = "یخچال"
                        },
                        new
                        {
                            Id = 6L,
                            BrandName = "بوش",
                            CategoryId = 2L,
                            Description = "-----",
                            Price = 8000000m,
                            ProductName = "جاروبرقی"
                        });
                });

            modelBuilder.Entity("Shop.Domain.Product", b =>
                {
                    b.HasOne("Shop.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
